#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: life
#+FILETAGS:life
#+SEQ_TODO: TODO NEXT DRAFT DONE
#+FILETAGS: life
#+HUGO_AUTO_SET_LASTMOD: t
#+SETUPFILE: ~/.spacemacs.d/org-templates/cnpost.org


* life
  [2017-09-27 Wed 22:18]

** DONE 我的回忆
   CLOSED: [2017-12-18 Mon 18:03]
   :PROPERTIES:
   :EXPORT_FILE_NAME: my-memory
   :EXPORT_DATE: [2017-09-27 Wed]
   :END:
   :LOGBOOK:
   - CLOSING NOTE [2017-12-18 Mon 18:03] \\
     done
   :END:

   今天我准备写一写我的回忆，我很少这么郑重去写回忆，总感觉时间还有很多，一年又一年，无穷无尽，至少。让我下这个决定的是我的妈妈，她得了奇怪的癌症，奇怪到连医生也难以给这个癌症起个名字。一年多的化疗夺走了她的头发和精气神。每次和她微信视频她都要捋一捋自己越来越少的头发，她不希望我们看到她现在这个样子，但是她也没有办法，至好偷偷的抹眼泪。她看上去很痛苦，很虚弱，而且还会继续痛苦和虚弱下去，直到。。。。我不敢微信视频，不愿接受现实。这还是我的妈妈么？

   我不知道要怎么组织我的思绪，总之很乱，我也无法给我母亲的一生下一个定论。我写不下去了，要掉眼泪了。从同年到现在所有的回忆都涌上心头，我想抓紧把它们记下来，害怕时间把这些记忆冲走，可是我越害怕，就越不知道开始从哪些地方开始。我就任由这思绪像流水一样从心头流过，心痛了我就赶紧捧起一捧，存起来。

   我的母亲是从山的那一边嫁到山的这一边的。她和我的父亲是通过媒人认识的。至于媒人怎么介绍，我就不知道了。母亲兄妹六个，她是家里最小的孩子，家里人都很宠。父亲是家里哥俩两个，父亲是老大。


** DONE 666 小聚                                :@life:666:
   CLOSED: [2017-10-11 Wed 02:02]
   :PROPERTIES:
   :EXPORT_FILE_NAME: 666-hang-out
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :thumbnailImage /img/life/20171011666.png
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :coverImage /img/life/friend.png
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :thumbnailImagePosition left
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :coverSize partial
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :showSocial false
   :EXPORT_DATE: [2017-10-11 Wed 01:19]
   :END:
   :LOGBOOK:
   - CLOSING NOTE [2017-10-11 Wed 02:02]
   CLOCK: [2017-10-11 Wed 01:24]--[2017-10-11 Wed 02:02] =>  0:38
   CLOCK: [2017-10-11 Wed 01:19]--[2017-10-11 Wed 01:20] =>  0:01
   :END:

#+begin_quote
如果能有这么一群人一直陪着喝酒，也是幸福生活加分项。
#+end_quote
#+INCLUDE: ./life/666-hang-out-20171011.org :only-contents t
** DONE 重新架构世界               :reading:@reading:@life:
CLOSED: [2018-02-19 Mon 11:02]
:PROPERTIES:
:EXPORT_FILE_NAME: quantum-physics-gossip
:EXPORT_DATE: <2018-02-19 Mon 09:03>
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :summary "《量子物理史话》读后感"
:END:
:LOGBOOK:
CLOCK: [2018-02-19 Mon 09:05]--[2018-02-19 Mon 10:51] =>  1:46
:END:
*** 简介
[2018-02-19 Mon 09:22]

很早的时候，在我的多看书架上，就有了这本书。今天得空，一睹为快。一直以
来我觉得一本书能不能让读者手不释卷，有一半的责任在作者。本书作者曹天元
出色的完成了自己的那一半。对于我这种有工科背景的读者，借助此书一窥量子
物理的发展史，这本书可以堪此大任。从可读性来讲，比霍金的《时间简史》读
起来更令人愉悦。读书，不愉悦，毋宁死。

*** 三次波粒世界大战
[2018-02-19 Mon 09:21]

这本书最精彩的部分在波粒二象性的三次世界。关于光的本质，作者用其高超的
故事技能，娓娓道来300年的波粒战争史。三百年来，兴废存亡，朝代更迭，沧
海桑田。无数物理大家你方唱罢我登场，犹如在演绎量子物理精彩绝伦的舞台剧。

全书从赫兹发现电磁波开始讲起，在讲述赫兹发现电磁波的实验过程中，作者提
了一笔：赫兹在实验报告中提及当他把铜缆线圈放到光照下时发现电火花出现的
更强烈。若非赫兹英年早逝，赫兹应该会同时发现光的波粒二象性。历史没有假
设，从那时起，关于光的本质引无数物理英雄尽折腰。
**** 第一次波粒世界大战
[2018-02-19 Mon 09:48]

波动说军团的弹药库里有：
1. 格里马第的光衍射试验（有以太这个累赘）；
2. 胡克重复了格里马第的工作，断定光必定是某种快速的脉冲。撰写《显微术》
   明确支持波动说。
3. 惠更斯继承胡克学说，认为光是一种在以太里传播的纵波。出版了著作《光
   环》

微粒说军团的弹药库里有：
1. 牛顿光环。牛顿解释光色散试验说明光是由不同颜色的微粒构成。牛顿开始
   还在波粒之间摇摆不定，后来跟胡克干上了，“赌气”似的一边倒支持微粒说。
2. 1665年，牛顿发现了牛顿环。
3. 1704年，牛顿发表煌煌巨著《光学》。把波的一些概念（如振动和周期）引
   入微粒，巧妙的回答了牛顿环的问题。

鉴于牛顿光环，波动学说一溃千里，微粒学说占尽风头。惠更斯去世，波动说群
龙无首，几乎丧失所有阵地。第一次波粒世界大战的结果是波粒说占据了物理学
界的主流，波动转入地下，开始了长达一个世纪的忍辱负重。
**** 第二次波粒世界大战
[2018-02-19 Mon 09:59]

波动说军团的弹药库里有：
1. 托马斯杨的双缝干涉试验。用光的干涉效应解释牛顿环和衍射现象。发表
   《自然哲学讲义》；
2. 菲涅尔提出了光是横波；严密的数学推理解释了光的衍射；在1818年论文大
   奖赛上，当场打脸泊松。泊松提出按照菲涅尔的理论，在圆盘衍射实验中，
   应该有个亮斑出现在阴影中间。菲涅尔的助手阿拉果坚持当场试验检测，结
   果泊松被打脸。人们还命名这个亮斑为“泊松亮斑”，心疼泊松五秒钟。
3. 傅科测定光速。
4. 美的令人窒息的麦克斯韦方程组，统领整个电磁世界。击碎了微粒说的所有
   幻想，预言光是一种电磁波，赫兹证明了这个预言。

微粒说军团的弹药库里有：
1. 牛顿的粒子学说早已深入人心，这些人包括扩比奥，拉普拉斯和泊松；
2. 1809年马吕斯发现偏振现象和已有的波动学说相抵触；

第二次波粒世界大战以微粒学说惨败告终。物理学迎来了黄金时代。人们认为物
理学已经尽善尽美，后人只需要在这个架构上修修补补就可以去海边晒太阳了。
但是赫兹的那个实验中还有一个奇怪的现象：当有光照射到那个铜缆线圈的缺口
上时，似乎火花就出现的更容易一些。
**** 第三次波粒世界大战
[2018-02-19 Mon 10:18]

两朵乌云开始出现在物理学大厦上空，随时引发狂风暴雨。这两朵乌云是：
1. 迈克尔逊-莫雷试验中“以太”假设的存在与实验结果大相径庭；
2. “黑体辐射实验和理论的不一致”；

开尔文在一次演讲中提到了这两朵乌云，但是在场的所有人都没有意识到这两朵
乌云的意义。一场风暴就要来了。
1. 第一朵乌云导致了相对论革命的爆发；
2. 第二朵乌云导致了量子论革命的爆发；

波动说军团的弹药库里有：
1. 黑体辐射从类波的角度推导，就得到适用于长波的瑞利-金斯公式；
2. 麦克斯韦方程组；
3. 光的双缝干涉试验；
4. 泊松亮斑；
5. 德布罗意波的发现；
6. 薛定谔方程的发明；


微粒说军团的弹药库里有：
1. 黑体辐射从粒子的角度推导，就得到适用于短波的维恩公式；
2. 普朗克（量子物理奠基人）打开了潘多拉盒子，普朗克黑体公式适合所有波
   长。普朗克认为： *必须假定能量在发射和吸收的时候，不是连续不断的而是
   分成一份一份的* 。开启了全新的物理学研究
3. 1905年，爱因斯坦发现光电效应 \(E=hv\)，提出光子概念；
4. 康普顿效应，发现x射线是一种量子现象。上帝制造了光，爱因斯坦指出什么
   是光，康普顿看到了光；
5. 海森堡的矩阵力学；狄拉克推进了数学表达；

第三次波粒世界大战引发了量子革命，光的波粒二象性被发现。波尔到了卢瑟福
开的诺贝尔幼儿园之后就一发不可收拾，创建了哥本哈根学派，并一直统领量子
物理的研究。不确定原理被发现，人们试图创建一个大一统的理论去描述这个世
界。

虽然光的波粒二象性被发现，但是关于如何认识解释二象性，如何认识世界，诸
多物理学家还在苦苦的解释；目前针对物理世界的解释出现了众多纷繁的观点最
有名的是哥本哈根解释和多世界解释。在此就不再展开了。


*** 杂记
[2018-02-19 Mon 09:21]

看到知乎上有人评价说曹天元写了《量子物理史话》之后应该再接再厉。去做传
媒和理财规划完全是浪费人才。这绝对不会是我的留言风格。我尊重别人的选择，
并认为自己无权过问和评论别人的选择。与我而言，感受到的只是读书时的畅快
淋漓和击节而叹。余光中老先生说得对，你只需要知道鸡蛋好吃，何必在意那只
下蛋的母鸡长什么样？同样，我也不会去评论余光中的生活和为人，我只知道他
的诗文简直帅到极点。
