#+TITLE: MATH
#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: math
#+FILETAGS: math
#+HUGO: more
#+SEQ_TODO: TODO NEXT DONE
#+HUGO_AUTO_SET_LASTMOD: t
#+hugo_front_matter_key_replace: description>summary
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../static/css/worg.css"  />
#+SETUPFILE: ~/.spacemacs.d/org-templates/math.org

* Math
** DONE toeplitz matrix
:PROPERTIES:
:EXPORT_FILE_NAME: toeplitz-matrix
:EXPORT_DATE: <2018-03-14 Wed 19:53>
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :summary "sommary of Toeplitz Matrix"
:END:
#+include: "./math-toeplitz-matrix.org"


bibliography:~/Dropbox/research_library/zcl.bib
bibliographystyle:unsrt

** DONE linear algebra done right
CLOSED: [2018-04-28 Sat 22:00]
:PROPERTIES:
:EXPORT_FILE_NAME: linear-algebra-done-right
:EXPORT_DATE: <2018-04-28 Sat 21:57>
:EXPORT_DESCRIPTION: My learning of linear algebra. Matrix should be the one of the math tool every engineer should have in hand.
:END:

 During the study of linear algebra, several asistant materials are
 referenced:
1. The opencourse 18.06 from [[http://www-math.mit.edu/~gs/][Gilbert Strang]]. From Strang's home, many
   valuable materials are available.
2. The textbook /Introduction to Linear Algebra/  by Gilbert Strang cite:Strang2016Aug.
3. The textbook /Linear Algebra Done Right/ by [[http://www.axler.net/][Sheldon Axler]] cite:Axler2014. You can
   get an abridged version of /Linear Algebra Done Right/ from Axler's
   homepage.
4. The textbook /Matrix Analysis and Applied Linear Algebra/ by [[http://meyer.math.ncsu.edu/][Carl D. Meyer]].

All the materials mentioned above have one important point in common.
Deteriminant is *not* located at the very beginning. The authors
arrange their books in a more desirable order taking the readers into
consideration. Take the determinants for example, many textbooks
arrange the determinants chapter at the very beginning. However, the
three books mentioned above put the determinants chapter at the near
end of the book. All the books mentioned above focus on the linear
space.

By following Professor Strang, I got an overview of the four spaces of
one matrix. Actually, I learnt the 18.06 from the MIT OCW more than
one time. After each time, my understanding of linear algebra was
deepened.



* Abstract Algebra
  [2017-12-18 Mon 19:26]


* Probability
  [2017-12-18 Mon 19:26]


bibliography:~/Dropbox/research_library/zcl.bib
bibliographystyle:unsrt
